### ISSUE TITLE
Zephyr website: missing most of the blog posts from previous site

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/infrastructure-old#176] opened 2019-11-26 22:36 UTC
As reported by Mae, "there are only 5 blogs listed but I think we assumed all of the blog and press release content will be moving over to this new site. Is that right? Please confirm."

The current site has 81 blog posts and Announcements, with these 34 posts from 2019:

- The Zephyr Project Welcomes Eclipse IoT and Oticon As Members to Create a Safe and Secure RTOS
- The Zephyr Project Announces Major Technical Milestone with New Long Term Support Code Release
- Zephyr – An Operating System for IoT
- Social Change in Open Source Software
- Co-simulating HDL models in Renode with Verilator running on Zephyr RTOS
- When 32 bits isn’t enough — Porting Zephyr to RISCV64
- Zephyr RTOS 2.0 Release Highlights
- Zephyr RTOS and Cortex-R5 on Zynq UltraScale+
- What’s new in Zephyr – 2.0.0rc1
- How to get and compile a Zephyr firmware
- KubeCon + CloudNativeCon + Open Source Summit China
- Zephyr Meetup @ The 1st Open Source IoT Projects Seminar in China
- What’s new in Zephyr, 28 June 2019
- Zephyr OS Helps Protect the Environment
- Zephyr RTOS featured in RISC-V Getting Started Guide
- What’s new in Zephyr – May 28, 2019
- Zephyr OS is ready for connected worker devices
- Zephyr Project F2F Meeting of the Minds
- Winners of the Zephyr Project bug fixing contest
- What Zephyr Project Members Had to Say about the new LTS release
- Learn more about Zephyr 1.14.0 LTS
- Zephyr LTS Preview
- Bluetooth LE Developer Study Guide V5.1
- Zephyr RTOS featured at Linaro Connect Bangkok 2019
- Zephyr OS 1.14 (LTS) Bug Fixing Contest
- Endian Technologies Hosts Zephyr Hackathon at FOSS North 2019
- Getting Started with Zephyr RTOS on Nordic nRF52832 hackaBLE
- ProGlove Introduces New IoT Wearable for Industrial, Logistics and Trade
- The Drones Flying Indoors During the Superbowl Halftime Show Featured Zephyr OS!
- The Zephyr Project Demonstrates IoT Innovation at Embedded World
- Zephyr Project RTOS – First Functional Safety Certification Submission for an Open Source Real Time Operating System
- Tech Radar: Open source may be the key to securing IoT
- New Year, New Milestones: What to Expect from the Zephyr Project in 2019
- Zephyr OS on display at CES

**Comment by Lloveday** [comment] 2019-12-01 23:18
This is complete

**Comment by kestewart** [comment] 2019-12-03 00:58
Per email from Mae today,  please put a date, and sort the blog entries so most recent first.

**Comment by mimeriza** [comment] 2019-12-03 01:07
Removed "Verify" label until the requested date and ordering are addressed.

**Comment by Lloveday** [comment] 2019-12-06 03:30
The ordering has been fixed, but I am still working on adding the date to the boxes.

**Comment by mimeriza** [comment] 2019-12-06 18:13
Duplicate of 188. Closing in favor of that issue.

**Closed as completed by mimeriza** 2019-12-06 18:13 UTC
Labels: priority: high, area: Website, Blocker
